/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio;

import javax.swing.JOptionPane;

/**
 *
 * @author aolivero11
 */
public class Vectorcuatro extends javax.swing.JFrame {

    /**
     * Creates new form Vectorcuatro
     */
    double v[];
    public Vectorcuatro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLong = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdLlenarMan = new javax.swing.JButton();
        cmdLlenarAuto = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmdRep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("  VECTOR QUE MAS SE REPITE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 350, 40));

        jPanel2.setBackground(new java.awt.Color(246, 221, 246));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dato inicial:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(102, 0, 102))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel2.setText("Longitud:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 70, -1));

        txtLong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongKeyTyped(evt);
            }
        });
        jPanel2.add(txtLong, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 100, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 230, 110));

        jPanel3.setBackground(new java.awt.Color(239, 222, 239));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(102, 0, 102))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 190, 140));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 230, 190));

        jPanel4.setBackground(new java.awt.Color(249, 232, 249));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(102, 0, 102))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel4.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 80, 30));

        cmdLlenarMan.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdLlenarMan.setText("Llenar Manual");
        cmdLlenarMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenarManActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLlenarMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 140, 30));

        cmdLlenarAuto.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdLlenarAuto.setText("Llenar Automatico");
        cmdLlenarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenarAutoActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLlenarAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        cmdMostrar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 90, 30));

        cmdBorrar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 80, 30));

        cmdRep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdRep.setText("Numero repetido");
        cmdRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRepActionPerformed(evt);
            }
        });
        jPanel4.add(cmdRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 140, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 220, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        int lg;
        
        if (txtLong.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Ingrese la longitud","Error",JOptionPane.ERROR_MESSAGE);
            txtLong.requestFocusInWindow();
        }
        else if (Integer.parseInt(txtLong.getText().trim())==0){
         JOptionPane.showMessageDialog(this, "La longitud no puede ser cero","Error",JOptionPane.ERROR_MESSAGE);
         txtLong.requestFocusInWindow();
         txtLong.selectAll();
        }
        else{
            lg=Integer.parseInt(txtLong.getText().trim());
            v= new double [lg];
            JOptionPane.showMessageDialog(this,"Vector creado!");
        }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdLlenarManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenarManActionPerformed
       double n;
        for (int i = 0; i < v.length; i++) {
           n=Double.parseDouble(JOptionPane.showInputDialog("Digite el elemento en la posicion"+i));
           v [i]=n;
        }
    }//GEN-LAST:event_cmdLlenarManActionPerformed

    private void cmdLlenarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenarAutoActionPerformed
         double n,n1;
         
         n1=Double.parseDouble(JOptionPane.showInputDialog(this, "Digite un numero hasta donde quiere el llenado:"));
         while (n1<v.length){
             JOptionPane.showMessageDialog(this,"Digite un numero mayor a: "+v.length);
             n1=Double.parseDouble(JOptionPane.showInputDialog(this,"Digite el numero hasta donde quiere el llenado"));
         }
        for (int i = 0; i <v.length; i++) {
            n=(int)(Math.random()* + 1);
            v[i]=1;
        }
    }//GEN-LAST:event_cmdLlenarAutoActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        txtResultado.append("Los elementos del vector 1 son ");
        for (int i = 0; i < v.length; i++) {
         txtResultado.append(v[i]+ "\n");
        }
        
        
      
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        txtLong.setText("");
        txtResultado.setText("");
        v= null;
        
        txtLong.requestFocusInWindow();
        
        
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtLongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongKeyTyped
        char c=evt.getKeyChar(); 

          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume();  
          }
    }//GEN-LAST:event_txtLongKeyTyped

    private void cmdRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRepActionPerformed
        double c=0,n2=0;
        
        for (int i = 0; i < v.length; i++) {
          double c1=0;
            for (int j = 0; j < v.length; j++) {
              if (v[i]==v[j]);
              c1=c1+1;
            }
            if (c1>c){
                n2=v[i];
                c=c1;
            }
        }
        txtResultado.setText("El numero que mas se repite es: "+n2);
    }//GEN-LAST:event_cmdRepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vectorcuatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vectorcuatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vectorcuatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vectorcuatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vectorcuatro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLlenarAuto;
    private javax.swing.JButton cmdLlenarMan;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdRep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtLong;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
